#!/usr/bin/env bash
# discovery/05-generate-selectors.sh -- Generate selectors config from discovery
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/../config/env.sh"

echo "=== Discovery Step 5: Generate Selectors ==="

SELECTORS_FILE="$SCRIPT_DIR/../config/selectors.sh"

# Collect discovered information from the live DOM
echo "  Querying DOM for selector patterns..."

# Get the add-block button selector
ADD_BTN_SEL=$($RODNEY_CMD js "
    (() => {
        const candidates = [
            { sel: 'button[title=\"Add\"]', el: document.querySelector('button[title=\"Add\"]') },
            { sel: 'button[title=\"Insert block\"]', el: document.querySelector('button[title=\"Insert block\"]') },
            { sel: '.c-sf-add-button', el: document.querySelector('.c-sf-add-button') },
            { sel: 'button[data-streamfield-block-count]', el: document.querySelector('button[data-streamfield-block-count]') },
        ];
        for (const c of candidates) {
            if (c.el) return c.sel;
        }
        return '';
    })()
" 2>/dev/null || echo "")

# Get the block chooser container selector
CHOOSER_SEL=$($RODNEY_CMD js "
    (() => {
        const candidates = [
            { sel: '.tippy-content', el: document.querySelector('.tippy-content') },
            { sel: '[role=\"menu\"]', el: document.querySelector('[role=\"menu\"]') },
            { sel: '.dropdown-menu', el: document.querySelector('.dropdown-menu') },
        ];
        for (const c of candidates) {
            if (c.el) return c.sel;
        }
        return '';
    })()
" 2>/dev/null || echo "")

# Get the page type link selector
PAGE_TYPE_SEL=$($RODNEY_CMD js "
    (() => {
        const link = document.querySelector('a[href*=\"add/${PAGE_TYPE_APP_LABEL}/${PAGE_TYPE_MODEL}/\"]');
        return link ? 'a[href*=\"add/${PAGE_TYPE_APP_LABEL}/${PAGE_TYPE_MODEL}/\"]' : '';
    })()
" 2>/dev/null || echo "")

# Get the publish button selector
PUBLISH_SEL=$($RODNEY_CMD js "
    (() => {
        const candidates = [
            { sel: 'button[name=\"action-publish\"]', el: document.querySelector('button[name=\"action-publish\"]') },
            { sel: '.action-save button[name=\"action-publish\"]', el: document.querySelector('.action-save button[name=\"action-publish\"]') },
        ];
        for (const c of candidates) {
            if (c.el) return c.sel;
        }
        return '';
    })()
" 2>/dev/null || echo "")

echo "  Discovered selectors:"
echo "    Add block button: ${ADD_BTN_SEL:-'(not found)'}"
echo "    Block chooser: ${CHOOSER_SEL:-'(not found)'}"
echo "    Page type link: ${PAGE_TYPE_SEL:-'(not found)'}"
echo "    Publish button: ${PUBLISH_SEL:-'(not found)'}"

# Write updated selectors file
echo "  Writing updated selectors to ${SELECTORS_FILE}..."

cat > "$SELECTORS_FILE" << 'SELEOF'
#!/usr/bin/env bash
# config/selectors.sh -- CSS selectors for Wagtail 6.x admin
# Auto-generated by discovery/05-generate-selectors.sh
# Manual edits will be overwritten on next discovery run.

# --- Login page ---
SEL_USERNAME='#id_username'
SEL_PASSWORD='#id_password'
SEL_LOGIN_SUBMIT='button[type="submit"]'

# --- Dashboard / sidebar ---
SEL_SIDEBAR='.sidebar-menu-item'

# --- Page explorer ---
SEL_ADD_CHILD_PAGE='a[href*="add_subpage"]'
SEL_PAGE_LISTING='.listing tbody'

# --- Page type selection ---
SELEOF

echo "SEL_PAGE_TYPE_LINK='${PAGE_TYPE_SEL}'" >> "$SELECTORS_FILE"

cat >> "$SELECTORS_FILE" << 'SELEOF'

# --- Page edit form ---
SEL_PAGE_TITLE='#id_title'
SEL_PAGE_SLUG='#id_slug'
SEL_EDIT_FORM='#page-edit-form'

# --- Action buttons ---
SELEOF

if [[ -n "$PUBLISH_SEL" ]]; then
    echo "SEL_ACTION_PUBLISH='${PUBLISH_SEL}'" >> "$SELECTORS_FILE"
else
    echo "SEL_ACTION_PUBLISH='.action-save [name=\"action-publish\"]'" >> "$SELECTORS_FILE"
fi

cat >> "$SELECTORS_FILE" << 'SELEOF'
SEL_ACTION_DRAFT='.action-save [name="action-draft"]'
SEL_ACTION_MENU_TOGGLE='.dropdown-toggle'

# --- Success messages ---
SEL_SUCCESS_MESSAGE='.messages .success'

# --- StreamField ---
SEL_STREAMFIELD_BODY='[data-contentpath="body"]'
SELEOF

echo "SEL_ADD_BLOCK_BUTTON='${ADD_BTN_SEL}'" >> "$SELECTORS_FILE"
echo "SEL_BLOCK_CHOOSER='${CHOOSER_SEL}'" >> "$SELECTORS_FILE"

cat >> "$SELECTORS_FILE" << 'SELEOF'

# --- Tabs ---
SEL_TAB_CONTENT='a[href="#tab-content"]'
SEL_TAB_PROMOTE='a[href="#tab-promote"]'
SEL_TAB_SETTINGS='a[href="#tab-settings"]'

# --- Draftail ---
SEL_DRAFTAIL_EDITOR='.Draftail-Editor'
SEL_DRAFTAIL_INPUT='input[type="hidden"]'
SELEOF

echo ""
echo "  Selectors file updated: ${SELECTORS_FILE}"
echo ""
echo "=== Discovery Step 5 complete ==="
